# importing the libraries
from crewai import LLM, Agent, Task, Process, Crew
from crewai.project import CrewBase, crew, agent, task
from dotenv import load_dotenv
load_dotenv()

llm = LLM(model="openrouter/nvidia/nemotron-3-ultra-550b-a55b:free", stream=True)


@CrewBase
class GameBuilder:
    """GameBuilder crew for generating Python games"""

    @agent
    def senior_software_engineer_agent(self) -> Agent:
        return Agent(
            role="Senior Software Engineer",
            goal="Write initial Python game code as a complete, single-file script.",
            backstory=(
                "You are an expert Python game developer, highly experienced with PyGame and building "
                "robust game logic. You write clean, well-documented, and fully functional code."
            ),
            allow_delegation=False,
            verbose=True,
            llm=llm            
        )
    
    @agent
    def qa_engineer_agent(self) -> Agent:
        return Agent(
            role = "QA Engineer",
            goal = "Review the generated code for syntax and logic errors, and fix any issues.",
            backstory =("You are a meticulous QA Engineer with a keen eye for bugs. Your attention to detail "
                "ensures that all software works flawlessly and follows best practices. You never miss an edge case."),
            allow_delegation = False,
            verbose = True,
            llm=llm
        )
    
    @agent
    def chief_qa_engineer_agent(self) ->Agent:
        return Agent(
            role = "Chief QA Engineer",
            goal = "Validate that the final code meets the required specifications and runs perfectly.",
            backstory = ("You are the final gatekeeper for code quality. You ensure that the final game "
                "matches the client's specifications completely and is ready to be played. You format "
                "your final output as clean, raw Python code."),
            allow_delegation = False,
            verbose = True,
            llm=llm

        )
    
    @task
    def code_task(self) -> Task:
        return Task(
            description="Write a complete Python game using PyGame based on this specification: {game}\n\n"
                "Ensure all game mechanics, screen dimensions, controls, and logic are contained within a "
                "single runnable file. Do not use external assets (like images or sounds) so the code runs immediately.",
            expected_output="Complete, runnable Python code for the requested game.",
            agent=self.senior_software_engineer_agent()
        )
    
    @task
    def review_task(self)->Task:
        return Task(
            description="Review the code generated by the Senior Software Engineer for the game: {game}.\n\n"
                "Check for syntax errors, variable scoping bugs, game loop efficiency, and ensure it correctly "
                "handles edge cases (like player boundaries). If you find issues, rewrite the code to fix them.",
            expected_output= "Reviewed and debugged Python code.",
            agent = self.qa_engineer_agent()
        )
    
    @task
    def validation_task(self) -> Task:
        return Task(
            description="Perform a final validation on the game code for the specification: {game}.\n\n"
                "Ensure that the code is complete, meets all original requirements, and uses PyGame correctly. "
                "Your final output must be ONLY the Python code and nothing else. No markdown wrappers or conversational text.",
            
            expected_output="The final, production-ready Python code.",
            agent=self.chief_qa_engineer_agent()
        )
    
    @crew
    def crew(self) -> Crew:
        return Crew(
            agents=self.agents,
            tasks = self.tasks,
            verbose=True,
            process=Process.sequential,
            tracing=True
        )
    

